import { ToolConfig, WorkStats, StudyPlanItem, AppConfig, AiConfig } from './types';

export const DEFAULT_SUPABASE_CONFIG = {
  url: 'https://lnwiqirwjeeeahsjgzwg.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxud2lxaXJ3amVlZWFoc2pnendnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTM0NTIsImV4cCI6MjA4NTQyOTQ1Mn0.t0Bv0CBl5CSrFe3VVaUNJXsnvtIN1sJ5y6J7tRTgWE0'
};

export const DEFAULT_AI_CONFIG: AiConfig = {
  baseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
  apiKey: 'sk-sp-3ddae8d35c224c59a41d01079fe88f21',
  model: 'qwen3-max-2026-01-23'
};

export const CREATE_TABLE_SQL = `-- 1. 启用 Row Level Security
-- 请确保在执行前已有 auth 用户，或者注册新用户后会自动关联数据

-- 2. 创建工作统计表
create table public.pm_work_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  resumes_analyzed integer default 0,
  knowledge_points integer default 0,
  questions_answered integer default 0,
  prototypes_created integer default 0,
  flowcharts_created integer default 0,
  prds_created integer default 0,
  roadmaps_created integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.pm_work_stats enable row level security;

create policy "Users can view own stats"
  on public.pm_work_stats for select
  using (auth.uid() = user_id);

create policy "Users can insert own stats"
  on public.pm_work_stats for insert
  with check (auth.uid() = user_id);

create policy "Users can update own stats"
  on public.pm_work_stats for update
  using (auth.uid() = user_id);

-- 3. 创建学习计划表
create table public.pm_study_plan (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  date date not null,
  task text not null,
  status text check (status in ('pending', 'completed', 'in-progress')) default 'pending',
  is_milestone boolean default false,
  suggestion text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.pm_study_plan enable row level security;

create policy "Users can view own plan"
  on public.pm_study_plan for select
  using (auth.uid() = user_id);

create policy "Users can insert own plan"
  on public.pm_study_plan for insert
  with check (auth.uid() = user_id);

create policy "Users can update own plan"
  on public.pm_study_plan for update
  using (auth.uid() = user_id);

-- 可选：插入示例数据（需要先登录并替换 YOUR_USER_ID）
-- insert into public.pm_work_stats (user_id, resumes_analyzed) values ('YOUR_USER_ID', 10);
`;

export const CREATE_MEMBER_SQL = `-- 会员管理表 SQL
-- 用于存储扩展的会员信息及自定义登录控制

create table public.pm_members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- 关联 auth.users UUID
  email text not null,
  password text, -- 存储管理后台设置的密码 (明文或简单加密，仅用于业务校验)
  name text,
  role text default 'member', -- member, admin
  status text default 'active', -- active, disabled
  expiration_date timestamp with time zone, -- 账号有效期
  joined_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.pm_members enable row level security;

-- 允许所有认证用户查看成员列表 (根据需求调整)
create policy "Authenticated users can view members"
  on public.pm_members for select
  using (auth.role() = 'authenticated');

-- 允许用户更新自己的信息
create policy "Users can update own profile"
  on public.pm_members for update
  using (auth.uid() = user_id);
  
-- 允许匿名读取 (用于登录前校验，生产环境建议配合 Edge Function)
create policy "Enable read access for all users"
  on public.pm_members for select
  using (true);

-- 仅供参考：插入管理员
-- insert into public.pm_members (email, name, role, password, expiration_date) values ('admin@example.com', 'Admin', 'admin', 'pmlaogao', '2099-12-31');
`;

export const DEFAULT_TOOLS: ToolConfig[] = [
  {
    id: 'resume-analyzer',
    name: '简历分析器',
    url: '#',
    iconName: 'FileSearch',
    description: '智能解析候选人简历，快速匹配岗位需求',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23eff6ff'/><path d='M140,40 h120 v120 h-120 Z' fill='white' stroke='%23334155' stroke-width='3' stroke-linejoin='round'/><path d='M160,70 h80 M160,90 h80 M160,110 h60' stroke='%2394a3b8' stroke-width='3' stroke-linecap='round'/><circle cx='220' cy='120' r='30' fill='%2360a5fa' fill-opacity='0.2' stroke='%23334155' stroke-width='3'/><line x1='245' y1='140' x2='270' y2='165' stroke='%23334155' stroke-width='4' stroke-linecap='round'/></svg>`
  },
  {
    id: 'study-plan',
    name: '学习计划管理助手',
    url: '#',
    iconName: 'CalendarCheck',
    description: '定制化PM成长路径，追踪学习进度',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23f0f9ff'/><rect x='130' y='40' width='140' height='120' rx='5' fill='white' stroke='%23334155' stroke-width='3'/><line x1='130' y1='70' x2='270' y2='70' stroke='%23334155' stroke-width='3'/><path d='M160,30 v20 M240,30 v20' stroke='%23334155' stroke-width='3' stroke-linecap='round'/><path d='M150,90 l10,10 l20,-20' stroke='%2310b981' stroke-width='3' fill='none'/><path d='M190,120 l10,10 l20,-20' stroke='%2310b981' stroke-width='3' fill='none'/></svg>`
  },
  {
    id: 'knowledge-factory',
    name: '知识工厂',
    url: '#',
    iconName: 'BrainCircuit',
    description: '沉淀产品方法论，构建个人知识图谱',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23f5f3ff'/><circle cx='150' cy='100' r='30' stroke='%23334155' stroke-width='3' fill='white' stroke-dasharray='5 3'/><path d='M200,100 a30,30 0 0,1 30,-30 a30,30 0 0,1 30,30 a30,30 0 0,1 -30,30 a30,30 0 0,1 -30,-30' fill='white' stroke='%238b5cf6' stroke-width='3'/><path d='M230,70 v-20 M230,130 v20 M200,100 h-20 M260,100 h20' stroke='%238b5cf6' stroke-width='2'/></svg>`
  },
  {
    id: 'qa-helper',
    name: '问题梳理助手',
    url: '#',
    iconName: 'HelpCircle',
    description: '协助拆解复杂业务问题，寻找最优解',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23fff7ed'/><path d='M120,60 h100 a20,20 0 0,1 20,20 v40 a20,20 0 0,1 -20,20 h-60 l-30,30 v-30 h-10 a20,20 0 0,1 -20,-20 v-40 a20,20 0 0,1 20,-20 Z' fill='white' stroke='%23334155' stroke-width='3'/><text x='155' y='125' font-family='sans-serif' font-size='60' fill='%23f97316' font-weight='bold'>?</text></svg>`
  },
  {
    id: 'prototype-gen',
    name: '产品原型生成器',
    url: '#',
    iconName: 'LayoutTemplate',
    description: 'AI辅助快速生成低保真原型图',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23f8fafc'/><rect x='100' y='40' width='200' height='130' rx='5' fill='white' stroke='%23334155' stroke-width='3'/><line x1='100' y1='70' x2='300' y2='70' stroke='%23334155' stroke-width='2'/><circle cx='120' cy='55' r='3' fill='%23334155'/><circle cx='130' cy='55' r='3' fill='%23334155'/><rect x='120' y='90' width='60' height='60' fill='%23e2e8f0' stroke='none'/><rect x='190' y='90' width='90' height='10' fill='%23cbd5e1'/><rect x='190' y='110' width='90' height='10' fill='%23cbd5e1'/><rect x='190' y='130' width='60' height='10' fill='%23cbd5e1'/></svg>`
  },
  {
    id: 'flowchart-gen',
    name: '流程图生成器',
    url: '#',
    iconName: 'GitMerge',
    description: '业务逻辑可视化，自动生成标准流程图',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23eff6ff'/><rect x='80' y='80' width='60' height='40' rx='5' fill='white' stroke='%23334155' stroke-width='3'/><path d='M200,70 L230,100 L200,130 L170,100 Z' fill='%23bfdbfe' stroke='%23334155' stroke-width='3'/><rect x='260' y='80' width='60' height='40' rx='15' fill='white' stroke='%23334155' stroke-width='3'/><line x1='140' y1='100' x2='170' y2='100' stroke='%23334155' stroke-width='2'/><line x1='230' y1='100' x2='260' y2='100' stroke='%23334155' stroke-width='2'/></svg>`
  },
  {
    id: 'prd-gen',
    name: '产品需求生成器',
    url: '#',
    iconName: 'FileText',
    description: '标准化PRD文档撰写，提升文档质量',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23fff1f2'/><rect x='150' y='40' width='100' height='130' fill='white' stroke='%23334155' stroke-width='3'/><line x1='170' y1='70' x2='230' y2='70' stroke='%23fb7185' stroke-width='3'/><line x1='170' y1='90' x2='230' y2='90' stroke='%23cbd5e1' stroke-width='2'/><line x1='170' y1='110' x2='230' y2='110' stroke='%23cbd5e1' stroke-width='2'/><line x1='170' y1='130' x2='200' y2='130' stroke='%23cbd5e1' stroke-width='2'/></svg>`
  },
  {
    id: 'roadmap-tool',
    name: '产品规划梳理工具',
    url: '#',
    iconName: 'Map',
    description: '制定产品路线图，明确版本迭代计划',
    image: `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 200'><rect width='400' height='200' fill='%23faf5ff'/><path d='M50,150 C100,150 100,50 200,50 C300,50 300,150 350,150' fill='none' stroke='%23334155' stroke-width='3' stroke-dasharray='10 5'/><circle cx='50' cy='150' r='5' fill='%23d8b4fe'/><circle cx='200' cy='50' r='5' fill='%23d8b4fe'/><circle cx='350' cy='150' r='5' fill='%23d8b4fe'/><line x1='350' y1='150' x2='350' y2='100' stroke='%23334155' stroke-width='2'/><path d='M350,100 L380,115 L350,130 Z' fill='%23a855f7' stroke='%23334155' stroke-width='2'/></svg>`
  }
];

export const MOCK_STATS: WorkStats = {
  resumesAnalyzed: 124,
  knowledgePoints: 450,
  questionsAnswered: 89,
  prototypesCreated: 32,
  flowchartsCreated: 56,
  prdsCreated: 18,
  roadmapsCreated: 5
};

export const MOCK_STUDY_PLAN: StudyPlanItem[] = [
  {
    id: '1',
    date: '2024-05-20',
    task: '深入学习 A/B 测试方法论',
    status: 'completed',
    isMilestone: false,
    suggestion: '推荐阅读《A/B测试：创新互联网产品的科学方法》'
  },
  {
    id: '2',
    date: '2024-05-21',
    task: '完成电商后台订单模块原型设计',
    status: 'in-progress',
    isMilestone: true,
    suggestion: '重点关注逆向流程和异常状态处理'
  },
  {
    id: '3',
    date: '2024-05-22',
    task: '竞品分析报告：Notion vs Obsidian',
    status: 'pending',
    isMilestone: false,
    suggestion: '尝试从用户体验和数据结构两个维度进行对比'
  },
  {
    id: '4',
    date: '2024-05-25',
    task: 'SQL 进阶查询练习',
    status: 'pending',
    isMilestone: false,
    suggestion: '重点练习 JOIN 和窗口函数'
  },
  {
    id: '5',
    date: '2024-05-30',
    task: '月度产品复盘总结',
    status: 'pending',
    isMilestone: true,
    suggestion: '使用 STAR 原则梳理本月关键产出'
  }
];

export const MOCK_MEMBERS: any[] = [
  { id: 1, email: 'demo@example.com', name: '演示用户', role: 'member', status: 'active', joinedAt: '2024-01-01', password: 'password123', expirationDate: '2025-12-31' },
];